/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionId' : bigint, 'selectedIndex' : bigint }
export interface Question {
  'id' : bigint,
  'topic' : [] | [string],
  'answerIndex' : bigint,
  'questionText' : string,
  'options' : Array<string>,
  'points' : bigint,
}
export interface Submission {
  'answers' : Array<Answer>,
  'user' : Principal,
  'score' : bigint,
  'questionCount' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[Question], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrap_admin_role' : ActorMethod<[string, string], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getById' : ActorMethod<[bigint], Question>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMySubmissions' : ActorMethod<[], Array<Submission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubmissions' : ActorMethod<[Principal], Array<Submission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAnswers' : ActorMethod<[Array<Answer>], Submission>,
  'updateQuestion' : ActorMethod<[Question], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];