/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Opt(IDL.Text),
  'answerIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'points' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Answer = IDL.Record({
  'questionId' : IDL.Nat,
  'selectedIndex' : IDL.Nat,
});
export const Submission = IDL.Record({
  'answers' : IDL.Vec(Answer),
  'user' : IDL.Principal,
  'score' : IDL.Nat,
  'questionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bootstrap_admin_role' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getById' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnswers' : IDL.Func([IDL.Vec(Answer)], [Submission], []),
  'updateQuestion' : IDL.Func([Question], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Opt(IDL.Text),
    'answerIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'points' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Answer = IDL.Record({
    'questionId' : IDL.Nat,
    'selectedIndex' : IDL.Nat,
  });
  const Submission = IDL.Record({
    'answers' : IDL.Vec(Answer),
    'user' : IDL.Principal,
    'score' : IDL.Nat,
    'questionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([Question], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bootstrap_admin_role' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getById' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnswers' : IDL.Func([IDL.Vec(Answer)], [Submission], []),
    'updateQuestion' : IDL.Func([Question], [], []),
  });
};

export const init = ({ IDL }) => { return []; };